// <auto-generated />
using System;
using Formula_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Formula_1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Formula_1.Models.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrera"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.HasKey("IdCarrera");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("Formula_1.Models.Escuderia", b =>
                {
                    b.Property<int>("IdEscuderia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEscuderia"));

                    b.Property<int>("CantidadDePilotos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisDeOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PuntajeAcumulado")
                        .HasColumnType("int");

                    b.Property<string>("SponsorPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEscuderia");

                    b.ToTable("Escuderia");
                });

            modelBuilder.Entity("Formula_1.Models.Piloto", b =>
                {
                    b.Property<int>("NumeroPiloto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroPiloto"));

                    b.Property<int>("EscuderiaId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<string>("NombrePiloto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroAuto")
                        .HasColumnType("int");

                    b.Property<string>("PaisDeOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PuntajeAcumulado")
                        .HasColumnType("int");

                    b.HasKey("NumeroPiloto");

                    b.HasIndex("EscuderiaId");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("Formula_1.Models.Resultado", b =>
                {
                    b.Property<int>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResultado"));

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int");

                    b.Property<int>("IdPiloto")
                        .HasColumnType("int");

                    b.Property<int>("PosicionLlegada")
                        .HasColumnType("int");

                    b.Property<int>("PosicionSalida")
                        .HasColumnType("int");

                    b.HasKey("IdResultado");

                    b.HasIndex("IdCarrera");

                    b.HasIndex("IdPiloto");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("Formula_1.Models.Piloto", b =>
                {
                    b.HasOne("Formula_1.Models.Escuderia", "Escuderia")
                        .WithMany("Pilotos")
                        .HasForeignKey("EscuderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escuderia");
                });

            modelBuilder.Entity("Formula_1.Models.Resultado", b =>
                {
                    b.HasOne("Formula_1.Models.Carrera", "Carrera")
                        .WithMany("Resultados")
                        .HasForeignKey("IdCarrera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Formula_1.Models.Piloto", "Piloto")
                        .WithMany("Resultados")
                        .HasForeignKey("IdPiloto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Piloto");
                });

            modelBuilder.Entity("Formula_1.Models.Carrera", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("Formula_1.Models.Escuderia", b =>
                {
                    b.Navigation("Pilotos");
                });

            modelBuilder.Entity("Formula_1.Models.Piloto", b =>
                {
                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
